events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://ollama:11434;
            proxy_read_timeout 1200s;
            proxy_connect_timeout 1200s;
            proxy_send_timeout 1200s;
            proxy_set_header Host $host;
        }
    }
}
